### ISSUE TITLE
TypeError: <lambda>() got an unexpected keyword argument 'changedAt'

### ISSUE THREAD

**Issue by dubstepfuneral** [Lucino772/pymojang#3] opened 2021-11-13 17:17 UTC
Hi! I'm trying to write a python app involving the minecraft API and when trying to authenticate I get the error above.

Code: 
```
import mojang
import webbrowser

with open("SECRET.txt") as file:
    lines = file.readlines()
    id = lines[0][:-1]
    secret = lines[1]

app = mojang.microsoft_app(id, secret)
url = app.authorization_url(redirect_uri="https://google.com/")
webbrowser.open(url, 1, autoraise=True)
token = input("Enter token pls: ")
user = app.authenticate(auth_code=token, redirect_uri="https://google.com/")
```

**Comment by Lucino772** [comment] 2021-11-13 20:02
Duplicate of #2

**Closed by Lucino772** 2021-11-13 20:02 UTC
